### ISSUE TITLE
Cannot install django-taggit-templatetags

### ISSUE THREAD

**Issue by thedrow** [feuervogel/django-taggit-templatetags#13]
I'm on virtualenv and I'm trying to install this app but it does not work.
Here is the traceback:

(website) C:\Python27\environments\website\Scripts>pip install django-taggit-templatetags
Downloading/unpacking django-taggit-templatetags
  Downloading django-taggit-templatetags-0.4.6dev.tar.gz
  Running setup.py egg_info for package django-taggit-templatetags

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Python27\environments\website\Scripts\build\django-taggit-templatetags\setup.py", line 35, in <module>
    test_suite = "runtests.runtests"
  File "C:\Python27\Lib\distutils\core.py", line 152, in setup
     dist.run_commands()
  File "C:\Python27\Lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "<string>", line 12, in replacement_run
  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\egg_info.py", line 252, in find_sources
  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\egg_info.py", line 308, in run
  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\sdist.py", line 157, in read_template
  File "C:\Python27\Lib\distutils\command\sdist.py", line 315, in read_template
    self.filelist.process_template_line(line)
  File "C:\Python27\Lib\distutils\filelist.py", line 118, in process_template_line
    action, patterns, dir, dir_pattern = self._parse_template_line(line)
  File "C:\Python27\Lib\distutils\filelist.py", line 97, in _parse_template_line
    dir = convert_path(words[1])
  File "C:\Python27\Lib\distutils\util.py", line 203, in convert_path
    raise ValueError, "path '%s' cannot end with '/'" % pathname
ValueError: path 'taggit_templatetags/templates/taggit_templatetags/' cannot
```

 end with '/'
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info\django_taggit_templatetags.egg-info

writing requirements to pip-egg-info\django_taggit_templatetags.egg-info\require
s.txt

writing pip-egg-info\django_taggit_templatetags.egg-info\PKG-INFO

writing top-level names to pip-egg-info\django_taggit_templatetags.egg-info\top_
level.txt

writing dependency_links to pip-egg-info\django_taggit_templatetags.egg-info\dep
endency_links.txt

writing entry points to pip-egg-info\django_taggit_templatetags.egg-info\entry_p
oints.txt

writing manifest file 'pip-egg-info\django_taggit_templatetags.egg-info\SOURCES.
txt'

warning: manifest_maker: standard file '-c' not found

reading manifest file 'pip-egg-info\django_taggit_templatetags.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "C:\Python27\environments\website\Scripts\build\django-taggit-templatetags\setup.py", line 35, in <module>

```
test_suite = "runtests.runtests"
```

  File "C:\Python27\Lib\distutils\core.py", line 152, in setup

```
dist.run_commands()
```

  File "C:\Python27\Lib\distutils\dist.py", line 953, in run_commands

```
self.run_command(cmd)
```

  File "C:\Python27\Lib\distutils\dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "<string>", line 12, in replacement_run

  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\egg_info.py", line 252, in find_sources

  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\egg_info.py", line 308, in run

  File "C:\Python27\environments\website\lib\site-packages\setuptools-0.6c11-py2.7.egg\setuptools\command\sdist.py", line 157, in read_template

  File "C:\Python27\Lib\distutils\command\sdist.py", line 315, in read_template

```
self.filelist.process_template_line(line)
```

  File "C:\Python27\Lib\distutils\filelist.py", line 118, in process_template_line

```
action, patterns, dir, dir_pattern = self._parse_template_line(line)
```

  File "C:\Python27\Lib\distutils\filelist.py", line 97, in _parse_template_line

```
dir = convert_path(words[1])
```

  File "C:\Python27\Lib\distutils\util.py", line 203, in convert_path

```
raise ValueError, "path '%s' cannot end with '/'" % pathname
```

ValueError: path 'taggit_templatetags/templates/taggit_templatetags/' cannot end
 with '/'

---

Command python setup.py egg_info failed with error code 1
Storing complete log in C:\Users\Omer\AppData\Roaming\pip\pip.log

**Comment by ethemce** [comment]
i have exactly the same problem , did you find any solution ?

**Comment by zerocity** [comment]
me too

**Comment by ichi944** [comment]
oh me too

**Comment by ruedaminute** [comment]
Hey all, Streamweaver solved this install issue. Download his fork and then run python setup.py install. 
https://github.com/Streamweaver/django-taggit-templatetags
